version: "3.9"
services:
  fastapi:
    build:
      context: .
    container_name: fastapi
    environment:
      # Use Render's DATABASE_URL or an external one
      DATABASE_URL: postgresql://marketguru_data_user:2PRePLr1mLxqJtehIHHfUZCmWCzh0Zv6@dpg-ctif4vbtq21c73dnuc60-a.oregon-postgres.render.com/marketguru_data
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from your .env file
    volumes:
      - ./src:/app/src  # Mount source code for live updates during development
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
